name: Dlsite Eromanga Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # 01:00 JST
    - cron: '0 20 * * *'  # 05:00 JST
    - cron: '0 0 * * *'   # 09:00 JST
    - cron: '0 4 * * *'   # 13:00 JST
    - cron: '0 8 * * *'   # 17:00 JST
    - cron: '0 12 * * *'  # 21:00 JST

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-wordpress-xmlrpc
      - run: python Dlsite_Eromanga_Auto_Post.py
        env:
          AFFILIATE_ID: ${{ secrets.AFFILIATE_ID }}
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
